//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacmanConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PacmanConsole.ConsoleResources", typeof(ConsoleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               @,*#@
        ///              *%,#(
        ///             (,,,&amp;
        ///    .,,,,%%,*%.* ,,,,,,,%#
        ///    &amp;,*,,,,,@%.@%,,,,,@,#
        ///           #,,,&amp;@     .*
        ///           /*..#
        ///          @.,(,@
        ///          ,,,,&amp;/
        ///         @,,,,&amp;
        ///        @/,,,%@
        ///    #*@,,&amp;,,*,@/@,
        ///    ,#,#,#%#&amp;%/*/...
        /// </summary>
        internal static string DefeatPicture {
            get {
                return ResourceManager.GetString("DefeatPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the game!
        ///If you are reading this, you must be new at this game, so here are the rules.
        ///
        ///You are playing as Pacman, a yellow round fella, and your goal is to eat all dots in the maze. Sounds simple, right?
        ///Well, the bad news is that there are also four evil ghosts who want to catch you and tear your soul apart. Scary stuff.
        ///So let&apos;s restate your goal: you need to eat all dots AND not to get eaten by ghosts.
        ///
        ///There are four Power Pellets in the maze to help you in your task.
        ///When you eat o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      ,##.                   ,==.
        ///   ,#    #.                 \ o &apos;,
        ///  #        #     _     _     \    \
        ///  #        #    (_)   (_)    /    ;
        ///   `#    #&apos;                 /   .&apos;
        ///     `##&apos;                   &quot;==&quot;.
        /// </summary>
        internal static string IntroPicture {
            get {
                return ResourceManager.GetString("IntroPicture", resourceCulture);
            }
        }
    }
}
